version: '3.4'

services:
    client:
        build: .
        container_name: client
        environment: 
            - REACT_APP_MARCHAND_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYXJjaGFuZElkIjoiMSJ9.QNXpU-13PmKGN_3dBixiiKEayO-fiMN55XTVS81sfrw"
        ports:
            - 3003:3000
        volumes: 
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        stdin_open: true

    hub:
        image: selenium/hub
        container_name: hub
        ports:
            - 4444:4444

    chrome:
        image: selenium/node-chrome-debug
        container_name: chrome-debug
        environment: 
            - HUB_HOST=hub
        volumes: 
            - /dev/shm:/dev/shm
        depends_on: 
            - hub
        ports:
            - 5900:5900

    firefox:
        image: selenium/node-firefox-debug
        environment: 
            - HUB_HOST=hub
        volumes: 
            - /dev/shm:/dev/shm
        depends_on: 
            - hub
        ports:
            - 5901:5900